### ISSUE TITLE
IpldLink model validation fails

### ISSUE THREAD

**Issue by dananev** [MarshalX/atproto#338] opened 2024-06-16 17:17 UTC
Hi! Thanks for the SDK!

I was working with it and got a tiny issue. When you try to instantiate `IpldLink` with `link` field validation fails:
```
pydantic_core._pydantic_core.ValidationError: 1 validation error for IpldLink
$link
  Field required [type=missing, input_value={'link': 'bafkreia4linnhp...w34txua76r6kbphuf3vsia'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
```

To fix the issue either `link` should be declared with `serialization_alias` instead of plain `alias` or we should add `model_config` to `IpldLink`. 

```python
class IpldLink(BaseModel):
    """CID representation in JSON."""

    model_config = ConfigDict(populate_by_name=True)

    link: str = Field(alias='$link')  #: CID.
```

I can raise a small pull-request to fix the issue.

Thanks!

**Comment by dananev** [comment] 2024-06-16 19:39
Here or in the pull-request? Without aliases it's basically:
```json
{"link":"bafkreia4linnhpphw5fughdn3wok7okklggww34txua76r6kbphuf3vsia"}
````

I found out another thing. Probably, [ref](https://github.com/MarshalX/atproto/blob/main/packages/atproto_client/models/blob_ref.py#L21) in BlobRef shouldn't be `Union[str, IpldLink]`, but only `IpldLink`.
For example, this snippet returns 400:
```python
embed = models.AppBskyEmbedExternal.Main(
    external=models.AppBskyEmbedExternal.External(
        description="Yet another The Room gif",
        title="oh hi mark",
        uri="https://giphy.com/gifs/theroom-the-room-26CaLWA2dcqz6hS4U",
        thumb=BlobRef(
            mime_type="image/jpeg",
            size=316179,
            ref="bafkreia4linnhpphw5fughdn3wok7okklggww34txua76r6kbphuf3vsia",
        )
    )
)
    
record = client.send_post(
    text="https://giphy.com/gifs/theroom-the-room-26CaLWA2dcqz6hS4U",
    embed=embed,
)
```

Exception:
```
atproto_client.exceptions.BadRequestError: Response(success=False, status_code=400, content=XrpcError(error='InvalidRequest', message='Invalid app.bsky.feed.post record: Record/embed/external/thumb should be a blob ref'), headers={'Date': 'Sun, 16 Jun 2024 19:32:08 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '122', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'ETag': 'W/"7a-/Nk9d44dleWoqVCOpDSZq5x1q0M"', 'Vary': 'Accept-Encoding'})
```

**Comment by MarshalX** [comment] 2024-06-16 20:39
Well, the ref could be in raw and in JSON formats. Also, there is a deprecated blob type and a new one. this class tries to support everything in one

https://atproto.com/specs/data-model#blob-type

> ref (link, required): CID reference to blob, with multicodec type raw. In JSON, encoded as a $link object as usual

**Comment by MarshalX** [comment] 2024-06-16 20:45
> Without aliases it's basically:
> {"link":"bafkreia4linnhpphw5fughdn3wok7okklggww34txua76r6kbphuf3vsia"}

that's strange because we have test for it:

https://github.com/MarshalX/atproto/blob/d32f836fffbdc1e3c37be7c6332c809479f34f1b/tests/test_atproto_client/models/tests/test_blob_ref.py#L6-L17

**Comment by MarshalX** [comment] 2024-06-16 21:12
@dananev It is a sporadic case when you want to create a ﻿`BlobRef` by yourself. Typically, it is returned, for example, in a firehose as raw bytes. When you call a function like ﻿upload_blob, the process goes through XRPC, which communicates using JSON. Therefore, the response will be in the ﻿`$link` format. If you are trying to construct a ﻿`BlobRef` to use it with XRPC (specifically with the ﻿`send_post` method), you will need to create it in a JSON-compatible format.

So instead of 

```python
blob_ref = BlobRef(
        mime_type='text/plain',
        size=0,
        ref='blabla',
)
```

you need to do 

```python
blob_ref = BlobRef(
    mime_type='text/plain',
    size=0,
    ref=IpldLink(link='blabla'),
)
```

I fixed this kind of creation in the linked PR. Probably it could be a good idea to have methods in `BlobRef` which will convert between representations. RAW and JSON.

I still can't reproduce the initial issue :(

**Closed** 2024-06-16 21:30 UTC

**Comment by MarshalX** [comment] 2024-06-16 21:31
@dananev please try to create BlobRef as I mentioned above using SDK from the main branch. It should work fine with `send_post`. This bug fix will be included in the next release 

To install SDK from the main branch: 
```shell
pip uninstall atproto
pip install git+https://github.com/MarshalX/atproto.git@main
```

**Comment by dananev** [comment] 2024-06-17 19:21
All good now, thank you for the quick fix!

**Comment by MarshalX** [comment] 2024-06-20 22:11
@dananev FYI https://github.com/MarshalX/atproto/pull/348
