### ISSUE TITLE
Please allow typing-extensions>=4.8.0

### ISSUE THREAD

**Issue by escapedcat** [MarshalX/atproto#193] opened 2023-12-10 05:46 UTC
Would like to atproto use it with fastapi, but getting:

```sh
The conflict is caused by:
    The user requested typing_extensions
    atproto 0.0.31 depends on typing-extensions<4.8.0 and >=4.6.1
    fastapi 0.104.1 depends on typing-extensions>=4.8.0
```

Thanks for your work!

Related to #102

**Comment by MarshalX** [comment] 2023-12-10 11:18
Hi! The problem is typing extensions dropped support of Python 3.7 in 4.8.0. That's why it doesn't supported. So maybe I should drop it too because of EOL. Or maybe allow it and hope that this package will be resolved to <4.8.0 on Python 3.7

**Comment by escapedcat** [comment] 2023-12-11 02:42
[<img width="1121" alt="image" src="https://github.com/MarshalX/atproto/assets/1016218/deedf502-9d51-4a1d-ab5f-4a67d9fcd536">
](https://www.python.org/downloads)

Ah, got it! Thanks. Up to you, but kinda make sense to move with the main python version I guess.

**Comment by MarshalX** [comment] 2023-12-11 07:26
I started working on in but I have issue with pydantic https://github.com/MarshalX/atproto/pull/195. Maybe I'll lock pydantic more precisely to not block you with that

**Comment by escapedcat** [comment] 2023-12-11 07:29
No need to unblock me. It's not crucial for me. Was just wondering.

**Comment by MarshalX** [comment] 2023-12-11 11:08
closed in https://github.com/MarshalX/atproto/pull/195 will be included in the next release

**Closed by MarshalX** 2023-12-11 11:08 UTC

**Comment by MarshalX** [comment] 2023-12-11 13:44
pls verify in v0.0.32

**Comment by escapedcat** [comment] 2023-12-12 03:56
Works, thanks!
